services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_ROOT_PASSWORD: app
    ports:
      - "127.0.0.1:3316:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "mysql"

  redis:
    image: redis
    ports:
      - "6389:6379"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "redis"

  rabbitmq:
    build:
      context: ./rabbitmq-with-stomp-docker
    ports:
      - "5673:5672"
      - "15673:15672"
      - "61614:61613"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "rabbitmq"

  minio:
    image: minio/minio:latest
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "minio"

  spring-app-1:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
      - redis
      - rabbitmq
      - minio
    restart: always
    ports:
      - "127.0.0.1:8090:8080"
      - "5005:5005" # Debug port
    environment:
      - SPRING_PROFILES_ACTIVE=docker-compose
      - LOGGING_FILE_NAME=/var/log/spring-app/application.log
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_EXTERNAL_ENDPOINT=http://172.19.0.1:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    volumes:
      - ./logs:/var/log/spring-app
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "instagram-backend"

  spring-app-2:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
      - redis
      - rabbitmq
      - minio
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=docker-compose
      - LOGGING_FILE_NAME=/var/log/spring-app/application.log
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_EXTERNAL_ENDPOINT=http://172.19.0.1:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    volumes:
      - ./logs:/var/log/spring-app
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "instagram-backend"

  nginx:
    image: nginx:1.13
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - spring-app-1
      - spring-app-2
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "nginx"

  frontend:
    build:
      context: ../fe-instagram
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3001:80"
    depends_on:
      - nginx
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "instagram-frontend"

volumes:
  minio_data:
